### ISSUE TITLE
Deployment failure due to new property subscriptionRequired

### ISSUE THREAD

**Issue by lfalck** [MLogdberg/APIManagementARMTemplateCreator#51]
Hi!

Looks like MS added a new field in the API settings called "Subscription required". 

When i deploy a generated template with this property i get the following error:  "SubscriptionRequired property is not supported for versions before 20180601"

I just removed it from the generated template and it worked again.

Best regards,
Ludvig Falck

**Comment by Geronius** [comment]
Hello,

I've fixed this issue in PR #50 . When it is merged it will not be added to the template.

Beste regards

**Comment by lfalck** [comment]
Great, thanks!

**Comment by nilshedstrom** [comment]
I pill request 52 I fixed the bug by changing the Apiversion to 2018-06-01preview if the property SubscriptionRequired was present. 
I guess we need to decide on how to fix the problem. 
Maybe introduce a new parameter?

**Comment by Geronius** [comment]
I removed my solution because Nils his solution was beter. Hopefully it will be merged soon.

**Comment by MLogdberg** [comment]
So shall I merge both 50 and 52?


Med vänlig hälsning,
Mattias

Skickat från min iPhone

9 mars 2019 kl. 15:32 skrev Geronius <notifications@github.com<mailto:notifications@github.com>>:


I removed my solution because Nils his solution was beter. Hopefully it will be merged soon.

**Comment by nilshedstrom** [comment]
To solve this issue you only need to merge pull request #52.
@Geronius removed his fix from #50 so it safe to merge it at any time (it will not cause any problems for my fix in #52).

**Comment by MLogdberg** [comment]
This is merged now and should be solved!

**Comment by lfalck** [comment]
I am still getting the property but the version is 2017-03-01, do i need to change something when generating the template?

```powershell
Get-APIManagementTemplate -APIFilters $apiFilters -APIManagement $apiManagementName `
-ResourceGroup $resourceGroupName -SubscriptionId $subscriptionId `
-ExportAuthorizationServers $false -ExportPIManagementInstance $false `
-ExportGroups $false -ExportProducts $false -ParametrizePropertiesOnly $true | Out-File $fileName
```
```json
{
      "comments": "Generated for resource /subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxx/resourceGroups/xxxxx/providers/Microsoft.ApiManagement/service/xxxxxx/apis/xxxxx",
      "type": "Microsoft.ApiManagement/service/apis",
      "name": "[concat(parameters('service_xxxx_name'), '/xxxxx')]",
      "apiVersion": "2017-03-01",
      "properties": {
        "displayName": "XXX XXX",
        "apiRevision": "[parameters('xxx_apiRevision')]",
        "description": "xxx",
        "subscriptionRequired": true,
        "serviceUrl": "[parameters('xxx_serviceUrl')]",
        "path": "xxx",
        "protocols": [
          "https"
        ],
        "authenticationSettings": {
          "oAuth2": null,
          "openid": null
        },
        "subscriptionKeyParameterNames": {
          "header": "Ocp-Apim-Subscription-Key",
          "query": "subscription-key"
        },
        "isCurrent": "[parameters('xxx_isCurrent')]"
      }
```

**Comment by MLogdberg** [comment]
Sorry, missed to kick of the release... 
Here is a new version from PowerShell Gallery
https://www.powershellgallery.com/packages/APIManagementTemplate/1.4.42

**Comment by lfalck** [comment]
I actually used a build of the repo, but i tried the gallery now as well and got the same result.

**Comment by nilshedstrom** [comment]
Sorry, I did not realize that you were not using Write-APIManagementTemplates.

I made a new pull request #53 were I moved my fix so that it solves this issue for everyone.

**Comment by lfalck** [comment]
I should have included that information in the original issue, sorry. Thanks to everyone for the help!

**Comment by lfalck** [comment]
Confirmed working, you can close this, thanks!
